FROM fedora:33
RUN dnf update -y && \
    dnf install -y python3 && \
    dnf clean all

VOLUME /result
COPY check_openssl_conf.py /
RUN /check_openssl_conf.py
ENTRYPOINT /check_openssl_conf.py > /result/result.json
