FROM ubuntu:focal
RUN apt update && \
    apt upgrade -y && \
    apt install -y python3 && \
    apt clean

ENV DISTRO_TRUSTSTORE_NAME="Ubuntu Groovy"
ENV PYTHON="python3"

COPY check_openssl_conf.py entrypoint.sh /
RUN /entrypoint.sh
ENTRYPOINT /entrypoint.sh
