FROM debian:testing
RUN apt update && \
    apt upgrade -y && \
    apt install -y python3 ca-certificates && \
    apt clean

ENV DISTRO_TRUSTSTORE_NAME="Debian testing with ca-certificates"
ENV PYTHON="python3"

COPY check_openssl_conf.py entrypoint.sh /
RUN /entrypoint.sh
ENTRYPOINT /entrypoint.sh

