FROM openwrtorg/rootfs:x86-64
RUN mkdir -p /var/lock && \
    opkg update && \
    opkg install python3

ENV DISTRO_TRUSTSTORE_NAME="OpenWRT RootFS"
ENV PYTHON="python3"

COPY check_openssl_conf.py entrypoint.sh /
RUN /entrypoint.sh
ENTRYPOINT /entrypoint.sh
