FROM archlinux:latest
RUN pacman -Sy && pacman --noconfirm -S python3

ENV DISTRO_TRUSTSTORE_NAME="archlinux:latest"
ENV PYTHON="python3"

COPY check_openssl_conf.py entrypoint.sh /
RUN /entrypoint.sh
ENTRYPOINT /entrypoint.sh
