FROM fedora:33
RUN dnf update -y && \
    dnf install -y python3 && \
    dnf clean all

ENV DISTRO_TRUSTSTORE_NAME="Fedora 33"
ENV PYTHON="python3"

COPY check_openssl_conf.py entrypoint.sh /
RUN /entrypoint.sh
ENTRYPOINT /entrypoint.sh

