FROM opensuse/tumbleweed:latest
RUN zypper update -y && \
    zypper install -y python3

ENV DISTRO_TRUSTSTORE_NAME="openSUSE Tumbleweed"
ENV PYTHON="python3"

COPY check_openssl_conf.py entrypoint.sh /
RUN /entrypoint.sh
ENTRYPOINT /entrypoint.sh
