FROM ubuntu:focal
RUN apt update && \
    apt upgrade -y && \
    apt install -y python3 ca-certificates && \
    apt clean

COPY check_openssl_conf.py /
RUN /check_openssl_conf.py
ENTRYPOINT /check_openssl_conf.py
