FROM registry.access.redhat.com/ubi8/ubi-minimal
RUN microdnf update -y && \
    microdnf install -y python3 && \
    microdnf clean all

ENV DISTRO_TRUSTSTORE_NAME="RHEL 8.3 UBI"
ENV PYTHON="python3"

COPY check_openssl_conf.py entrypoint.sh /
RUN /entrypoint.sh
ENTRYPOINT /entrypoint.sh
