---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:
    types: rebuild
  workflow_dispatch:
    inputs:
      git-ref:
        required: false

jobs:
  distros:
    name: "Container ${{ matrix.distro }}"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        distro: [
          "alpine",
          "archlinux",
          "centos8",
          "debian-buster-ca-certificates", "debian-buster", "debian-testing", "debian-testing-ca-certificates",
          "fedora-32", "fedora-33", "fedora-34", "fedora-rawhide",
          "gentoo",
          "linuxmint-193",
          "opensuse-tumbleweed",
          "openwrt",
          "rhel8-ubi",
          "ubuntu-xenial-ca-certificates", "ubuntu-bionic-ca-certificates", "ubuntu-focal-ca-certificates", "ubuntu-focal", "ubuntu-groovy"
        ]
    steps:
      - name: checkout
        uses: "actions/checkout@v2"
      - name: "Build container ${{ matrix.distro }}"
        run: |
           set -xe
           docker build tools -f Dockerfile.${{ matrix.distro }} -t truststore:${{ matrix.distro }}
      - name: "Run container ${{ matrix.distro }}"
        run: |
          set -xe
          docker run truststore:${{ matrix.distro }} | tee result-${{ matrix.distro }}.json
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: result-${{ matrix.distro }}.json

  freebsd:
    runs-on: macos-latest
    name: FreeBSD with ca_root_nss
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: "actions/checkout@v2"
      - name: Run test in FreeBSD VM
        uses: vmactions/freebsd-vm@v0.0.8
        with:
          usesh: true
          prepare: pkg install -y python3 ca_root_nss
          run: |
            ./tools/check_openssl_conf.py > result-freebsd-ca_root_nss.json
      - name: Show results
        run: cat result-freebsd-ca_root_nss.json
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: result-freebsd-ca_root_nss.json

  analyze:
    name: "Analyze results"
    runs-on: "ubuntu-latest"
    needs:
      - distros
      - freebsd
    steps:
      - name: checkout
        uses: "actions/checkout@v2"
      - name: Download results
        uses: actions/download-artifact@v2
        with:
          name: result
      - name: "Run analyze script"
        run: tools/analyze_results.py | tee analyzed.json
      - uses: actions/upload-artifact@v2
        with:
          name: analyzed
          path: analyzed.json
